#!/usr/bin/env node
// standalone-link.mjs — make the standalone install unable to drift.
//
// `sync-standalone.mjs` copies this plugin's files over the compatibility
// entrypoints under the user's home. That works and it re-breaks on the next
// release: on 2026-08-26 twenty-nine files had drifted, the standalone gates
// were four days behind the plugin, and the owner read the drift notice and
// reasonably concluded the PLUGIN was stale. A sync you must remember is a
// sync that reports drift forever.
//
// So stop copying.
//
//   * A GATE becomes a forwarder that resolves the newest installed plugin at
//     call time and executes it. It has no version in it, so it never goes
//     stale and no release has to touch it. This is the half that matters:
//     a stale gate produces a WRONG VERDICT, and a verdict is the one thing
//     this project asks anyone to trust.
//   * A SKILL or TEMPLATE becomes a symlink, because Claude Code reads their
//     contents rather than executing them. A link still names one version, so
//     it is re-pointed by a later `--apply` — but a pointer is either right or
//     wrong, where eleven copies can be half-right and look fine.
//
// Windows needs no privilege for either. A `.cmd` forwarder is an ordinary
// file that PATHEXT resolves from the bare name, and a directory JUNCTION is
// available to an unprivileged user where a symlink is not.
//
// This writes outside any repository. Nothing here runs from a hook, no gate
// calls it, and it reports unless asked to write.
import { createHash } from 'node:crypto'
import {
  cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, readlinkSync, rmSync,
  symlinkSync, writeFileSync,
} from 'node:fs'
import os from 'node:os'
import path from 'node:path'

// The cache directory is built from the home directory rather than written
// down, exactly as the drift notice does. A plugin that hardcodes a path under
// someone's home is a plugin that depends on one.
export function cacheDirectory(homeDirectory = os.homedir()) {
  return path.join(homeDirectory, '.claude', 'plugins', 'cache', 'quality-harness',
    'quality-harness')
}

/**
 * The resolver a forwarder embeds: newest semver directory that still has a
 * `bin`, printed as an absolute path, empty when there is none.
 *
 * Deliberately not `sort -V` or a shell glob. macOS ships BSD sort, whose `-V`
 * cannot be relied on, and lexical order puts 2.0.4 above 2.0.10 — this cache
 * holds both. The comparison is numeric per component or it is wrong.
 */
export const RESOLVER = [
  'const f=require("fs"),p=require("path"),c=process.argv[1];',
  'let v=[];try{v=f.readdirSync(c)}catch{};',
  'v=v.map(n=>({n,m:/^(\\d+)\\.(\\d+)\\.(\\d+)$/.exec(n)}))',
  '.filter(x=>x.m&&f.existsSync(p.join(c,x.n,"bin")));',
  'v.sort((a,b)=>b.m[1]-a.m[1]||b.m[2]-a.m[2]||b.m[3]-a.m[3]);',
  'process.stdout.write(v.length?p.join(c,v[0].n):"")',
].join('')

/** Marks a file this tool generated, so a later run may replace its own work. */
export const FORWARDER_MARK = 'quality-harness-forwarder'

export function forwarderScript(gate, homeDirectory = os.homedir()) {
  const cache = cacheDirectory(homeDirectory).replace(homeDirectory, '$HOME')
  return [
    '#!/bin/sh',
    `# ${FORWARDER_MARK}: resolves the newest installed plugin at call time.`,
    '# Generated by standalone-link.mjs. No version appears here on purpose —',
    '# a copy goes stale, a forwarder cannot. Edit the plugin, not this file.',
    `cache="${cache}"`,
    `root=$(node -e '${RESOLVER}' "$cache" 2>/dev/null)`,
    'if [ -z "$root" ]; then',
    '  echo "quality-harness: no installed plugin under $cache, so this gate did not run." >&2',
    '  echo "quality-harness: nothing is blocked; install or update the plugin." >&2',
    // A missing plugin is the harness failing to run, never a finding about the
    // user's file. Exiting non-zero here would make a project's own gate fail
    // because a tool is absent, which is the block this harness removed.
    '  exit 0',
    'fi',
    `exec "$root/bin/${gate}" "$@"`,
    '',
  ].join('\n')
}

export function forwarderCmd(gate, homeDirectory = os.homedir()) {
  const cache = cacheDirectory(homeDirectory).replace(homeDirectory, '%USERPROFILE%')
  return [
    '@echo off',
    `rem ${FORWARDER_MARK}: resolves the newest installed plugin at call time.`,
    'rem Generated by standalone-link.mjs. PATHEXT includes .CMD, so the bare',
    'rem gate name the skills document resolves here under cmd and PowerShell.',
    'setlocal',
    `set "QH_CACHE=${cache}"`,
    'set "QH_ROOT="',
    `for /f "usebackq delims=" %%r in (\`node -e "${RESOLVER.replaceAll('"', '\\"')}" "%QH_CACHE%"\`) do set "QH_ROOT=%%r"`,
    'if not defined QH_ROOT (',
    '  echo quality-harness: no installed plugin under %QH_CACHE%, so this gate did not run.>&2',
    '  echo quality-harness: nothing is blocked; install or update the plugin.>&2',
    '  exit /b 0',
    ')',
    // The py launcher first: a Windows Python is `python.exe`, so `python3` —
    // the name the gate's shebang asks for — often does not exist there.
    `where /q py && (py -3 "%QH_ROOT%\\bin\\${gate}" %*) || (python "%QH_ROOT%\\bin\\${gate}" %*)`,
    '',
  ].join('\r\n')
}

const digest = file => {
  try { return createHash('sha256').update(readFileSync(file)).digest('hex') } catch { return null }
}

/**
 * Every digest this plugin has ever installed for `relative`, across the whole
 * cache. A file in the user's home matching one of these is a copy some earlier
 * `--apply` made; anything else may be the user's own work and is left alone.
 */
export function knownDigests(relative, homeDirectory = os.homedir()) {
  const cache = cacheDirectory(homeDirectory)
  const seen = new Set()
  let versions = []
  try { versions = readdirSync(cache) } catch { return seen }
  for (const version of versions) {
    const found = digest(path.join(cache, version, relative))
    if (found) seen.add(found)
  }
  return seen
}

const readOrEmpty = file => {
  try { return readFileSync(file, 'utf8') } catch { return '' }
}

const firstMeaningfulLine = text => text.split(/\r?\n/).find(line => line.trim()) ?? ''

/**
 * Whether `target` is the same artefact as `source`, by the line each kind uses
 * to identify itself. A digest match is the clean answer, but it only fires for
 * versions still in the cache — the standalone set here was four days old and
 * came from a version long since evicted, so digests alone called every real
 * plugin copy a stranger and the check protected nothing it was written for.
 *
 * A gate opens with `"""<name> — executable gate`; a template and a SKILL.md
 * open with a title or a frontmatter fence that names the same thing. Those
 * survive edits to the body, which is exactly what "drifted" means.
 */
export function sameLineage(target, source, kind) {
  if (kind === 'skill') {
    const name = /^name:\s*(\S+)/m.exec(readOrEmpty(path.join(target, 'SKILL.md')))?.[1]
    const expected = /^name:\s*(\S+)/m.exec(readOrEmpty(path.join(source, 'SKILL.md')))?.[1]
    return Boolean(name) && name === expected
  }
  const text = readOrEmpty(target)
  if (!text) return false
  if (kind === 'gate') {
    // Two shapes in this set, and only checking the first one silently refused a
    // real plugin copy: most gates open `"""<name> — description`, but
    // adr-retire-check opens with a sentence and no name at all. Compare the
    // subject where there is one, because the description drifts around it
    // (one named a home templates path, the next named the plugin), and the
    // whole opening line where there is not.
    const opening = body => body.split(/\r?\n/).slice(0, 4).find(line => line.startsWith('"""')) ?? ''
    const subject = line => /^"""([\w-]+)\s+—/.exec(line)?.[1] ?? null
    const here = opening(text)
    const there = opening(readOrEmpty(source))
    if (!here || !there) return false
    return subject(here) !== null || subject(there) !== null
      ? subject(here) === subject(there)
      : here === there
  }
  if (kind === 'shim') {
    // Either our forwarder or the copied shim it replaces, both of which name
    // the gate they run.
    return text.includes(FORWARDER_MARK) || /%~dp0[\w-]+/.test(text)
  }
  return firstMeaningfulLine(text) === firstMeaningfulLine(readOrEmpty(source))
}

/**
 * Whether this tool may overwrite `entry.to`. It qualifies when it is absent,
 * when it is a forwarder or link this tool wrote, when its contents match a
 * file some cached version installed, or when it identifies itself as the same
 * artefact. Anything else is reported and left alone.
 *
 * The home config directory holds the user's own tools beside ours — a memory
 * server, a palace backup, three skills this plugin never shipped. Writing a
 * path that merely shares a name would destroy work nobody asked us to touch.
 */
export function replaceable(entry, homeDirectory = os.homedir()) {
  const { to: target, relative, lineage } = entry
  let info
  try { info = lstatSync(target) } catch { return { ok: true, why: 'absent' } }
  if (info.isSymbolicLink()) {
    const points = (() => { try { return readlinkSync(target) } catch { return '' } })()
    return points.startsWith(cacheDirectory(homeDirectory))
      ? { ok: true, why: 'our link' }
      : { ok: false, why: 'a symlink to something outside this plugin' }
  }
  if (info.isFile() && readOrEmpty(target).includes(FORWARDER_MARK)) {
    return { ok: true, why: 'our forwarder' }
  }
  if (info.isFile() && knownDigests(relative, homeDirectory).has(digest(target))) {
    return { ok: true, why: 'a copy of a released file' }
  }
  if (info.isDirectory() !== (lineage === 'skill')) {
    return { ok: false, why: info.isDirectory() ? 'a directory where a file belongs' : 'not a directory' }
  }
  return sameLineage(target, entry.source ?? entry.target, lineage)
    ? { ok: true, why: 'a drifted copy of this same file' }
    : { ok: false, why: 'not a file this plugin installed — it may be your own' }
}

/** The gates a forwarder is generated for, read from the plugin rather than listed. */
export function gateNames(source) {
  try {
    return readdirSync(path.join(source, 'bin')).filter(name => !name.includes('.')).sort()
  } catch {
    return []
  }
}

/**
 * What `--apply` would do. `forwarder` entries carry their full text so the
 * caller writes exactly what was reported; `link` entries carry a target.
 */
export function linkPlan(source, homeDirectory = os.homedir(), platform = process.platform) {
  const home = path.join(homeDirectory, '.claude')
  const work = []

  for (const gate of gateNames(source)) {
    work.push({
      kind: 'forwarder',
      to: path.join(home, 'bin', gate),
      relative: path.join('bin', gate),
      contents: forwarderScript(gate, homeDirectory),
      source: path.join(source, 'bin', gate),
      lineage: 'gate',
      mode: 0o755,
    })
    // The .cmd sits beside it on every platform. A repository synced from macOS
    // and used from Windows is the normal case, and a shim generated only where
    // it runs is a shim that is never there when it is needed.
    work.push({
      kind: 'forwarder',
      to: path.join(home, 'bin', `${gate}.cmd`),
      relative: path.join('bin', `${gate}.cmd`),
      contents: forwarderCmd(gate, homeDirectory),
      source: path.join(source, 'bin', `${gate}.cmd`),
      lineage: 'shim',
      mode: 0o644,
    })
  }

  for (const name of (() => {
    try { return readdirSync(path.join(source, 'skills')) } catch { return [] }
  })()) {
    if (!existsSync(path.join(source, 'skills', name, 'SKILL.md'))) continue
    work.push({
      kind: 'link',
      to: path.join(home, 'skills', name),
      relative: path.join('skills', name),
      target: path.join(source, 'skills', name),
      lineage: 'skill',
      directory: true,
    })
  }

  for (const name of (() => {
    try { return readdirSync(path.join(source, 'templates')) } catch { return [] }
  })()) {
    work.push({
      kind: 'link',
      to: path.join(home, 'templates', name),
      relative: path.join('templates', name),
      target: path.join(source, 'templates', name),
      lineage: 'template',
      directory: false,
    })
  }

  return work.map(entry => ({ ...entry, ...currentState(entry, homeDirectory, platform) }))
}

function currentState(entry, homeDirectory, platform) {
  const permission = replaceable(entry, homeDirectory)
  if (!permission.ok) return { state: 'skipped', why: permission.why }
  if (entry.kind === 'forwarder') {
    // A forwarder carries no version, so identical text means there is nothing
    // to do — not merely that it is current, but that it can never fall behind.
    const same = (() => { try { return readFileSync(entry.to, 'utf8') === entry.contents } catch { return false } })()
    return same ? { state: 'current' } : { state: permission.why === 'absent' ? 'missing' : 'replaced' }
  }
  if (platform === 'win32' && !entry.directory) {
    // A file symlink needs SeCreateSymbolicLinkPrivilege; a junction covers
    // directories only. A template is a file, so Windows keeps a copy for those
    // and says so rather than failing at the end of a long run.
    return { state: 'copy-only', why: 'Windows has no unprivileged file symlink' }
  }
  let points = null
  try { points = lstatSync(entry.to).isSymbolicLink() ? readlinkSync(entry.to) : null } catch {}
  if (points === entry.target) return { state: 'current' }
  return { state: points ? 'repointed' : existsSync(entry.to) ? 'replaced' : 'missing' }
}

/** Where a run's originals are kept. One directory per run, never reused. */
export function backupRoot(stamp, homeDirectory = os.homedir()) {
  return path.join(homeDirectory, '.claude', '.quality-harness-backup', stamp)
}

/**
 * Copy what is about to be replaced, before replacing it.
 *
 * Asked for by the owner on 2026-08-27 — "i need to backup my original ones
 * first then" — and the right answer is that they should not have had to.
 * Every guarantee in this file is about not losing someone's work, and a
 * backup you must remember is the same failure as a sync you must remember.
 *
 * Returns the path written, or null when there was nothing there to keep.
 */
export function archive(entry, stamp, homeDirectory = os.homedir()) {
  let info
  try { info = lstatSync(entry.to) } catch { return null }
  const kept = path.join(backupRoot(stamp, homeDirectory), entry.relative)
  mkdirSync(path.dirname(kept), { recursive: true })
  // A symlink is recreated rather than copied through. `cpSync` with
  // verbatimSymlinks preserves a LIVE link, but it throws ENOENT on a dangling
  // one — and a dangling link is exactly what a home config directory collects,
  // because the checkout a skill pointed at gets moved. Losing the archive step
  // to an exception halfway through a run is how the originals go missing at the
  // moment they matter most. Proved by a mutation that stayed green until the
  // dangling case was tested.
  if (info.isSymbolicLink()) symlinkSync(readlinkSync(entry.to), kept)
  else cpSync(entry.to, kept, { recursive: true, preserveTimestamps: true, verbatimSymlinks: true })
  return kept
}

export function write(entry, stamp = null, homeDirectory = os.homedir()) {
  // The archive happens first or it does not happen. `write` is the only path
  // that removes anything, so putting the copy anywhere else leaves a caller
  // able to skip it.
  const kept = stamp ? archive(entry, stamp, homeDirectory) : null
  mkdirSync(path.dirname(entry.to), { recursive: true })
  if (entry.kind === 'forwarder') {
    rmSync(entry.to, { force: true })
    writeFileSync(entry.to, entry.contents, { mode: entry.mode })
    return kept
  }
  if (entry.state === 'copy-only') {
    rmSync(entry.to, { force: true })
    writeFileSync(entry.to, readFileSync(entry.target))
    return kept
  }
  rmSync(entry.to, { force: true, recursive: true })
  symlinkSync(entry.target, entry.to, entry.directory ? 'junction' : 'file')
  return kept
}
